language: python
python:
  - "3.4"
install:
  - pip install sphinx sphinx_rtd_theme
before_script:
  - cd doc
script:
  - make html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/html
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: documentation
