language: python
python:
  - "3.4"
install:
  - pip install sphinx sphinx_rtd_theme
  - pip install nose2
jobs:
  include:
    - stage: test
      before_script:
        - cd tests/unittests
      script:
        - nose2
    - stage: docs
      before_script:
        - cd doc
      script:
        - make html
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build/html
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages

